<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>funstock.market</groupId>
    <artifactId>fun-stock-market-jars-file</artifactId>
    <version>1.0.22</version>
    <packaging>pom</packaging>

    <modules>
        <module>funmarket-sd-mapper</module>
        <module>market-service-domin</module>
        <module>stock-engine-service-domin</module>
        <module>common-modules</module>
        <module>git-reader</module>
        <module>stock-analysis</module>
        <module>funmarket-broker</module>
    </modules>
    <properties>
        <funmarket-sd-mapper>1.0.7</funmarket-sd-mapper>
        <market-service-domin>1.0.19</market-service-domin>
        <stock-engine-service-domin>1.0.0</stock-engine-service-domin>
        <common-version>1.0.23</common-version>
        <git-reader>1.0.26</git-reader>
        <stock-analysis>1.0.20</stock-analysis>
        <funmarket-broker>1.0.13</funmarket-broker>
    </properties>

    <distributionManagement>
        <repository>
            <id>funMarket</id>
            <name>GitHub</name>
            <url>https://maven.pkg.github.com/funstockmarket-projects/fun-stock-market-jars-files</url>
        </repository>
    </distributionManagement>

</project>