marketAnalysis.gitReader.gitWeeklyPath =https://api.github.com/repos/Harshavardhan320/StocksMarket-XL/contents/weeklyPerformance
marketAnalysis.gitReader.gitYearlyPath =https://api.github.com/repos/Harshavardhan320/StocksMarket-XL/contents/yearlyPerformance
marketAnalysis.gitReader.gitMonthlyPath =https://api.github.com/repos/Harshavardhan320/StocksMarket-XL/contents/monthlyPerformance
marketAnalysis.gitReader.gitDailyPath =https://api.github.com/repos/Harshavardhan320/StocksMarket-XL/contents/dailyPerformance

